'use strict';
const $=id=>document.getElementById(id), data=window.NOTEBOOK_DATA;
const tabs=[...document.querySelectorAll('[role=tab]')];
function selectTab(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',active);t.tabIndex=active?0:-1;$(t.getAttribute('aria-controls')).hidden=!active});stopPlay()}
tabs.forEach((tab,i)=>{tab.onclick=()=>selectTab(tab);tab.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectTab(tabs[next]);tabs[next].focus()}}});
data.classes.forEach(c=>{const el=document.createElement('span');el.textContent=c;$('class-list').append(el)});
let image=new Image(), custom=false, turns=0, flipH=false, flipV=false, brightness=1, imageVersion=0;
const canvas=$('tissue-canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function draw(){if(!image.complete||!image.naturalWidth)return;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#e7eade';ctx.fillRect(0,0,600,600);ctx.save();ctx.translate(300,300);ctx.rotate(turns*Math.PI/2);ctx.scale(flipH?-1:1,flipV?-1:1);if(custom){const scale=Math.min(600/image.naturalWidth,600/image.naturalHeight);const w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,-w/2,-h/2,w,h)}else{ctx.drawImage(image,10,32,462,462,-300,-300,600,600)}ctx.restore();if(brightness!==1){const pixels=ctx.getImageData(0,0,600,600);for(let i=0;i<pixels.data.length;i+=4)for(let c=0;c<3;c++)pixels.data[i+c]=255*Math.pow(pixels.data[i+c]/255,1/brightness);ctx.putImageData(pixels,0,0)}$('flip-h').setAttribute('aria-pressed',flipH);$('flip-v').setAttribute('aria-pressed',flipV);$('gamma-value').value=brightness.toFixed(1)+'×';$('transform-state').textContent=turns||flipH||flipV||brightness!==1?'TRANSFORMED':'ORIGINAL';}
function reset(){turns=0;flipH=false;flipV=false;brightness=1;$('gamma').value=1;draw()}
function sample(){imageVersion++;custom=false;image=new Image();image.onload=()=>{reset();$('image-status').textContent=''};image.onerror=()=>{$('image-status').textContent='The sample could not load. Please refresh the page.'};image.src='cell-14-1.png';$('image-name').textContent='NOTEBOOK SAMPLE';$('image-caption').textContent='A tissue image from the original notebook';$('restore-sample').hidden=true;$('image-upload').value=''}
$('flip-h').onclick=()=>{flipH=!flipH;draw()};$('flip-v').onclick=()=>{flipV=!flipV;draw()};$('rotate').onclick=()=>{turns=(turns+1)%4;draw()};$('gamma').oninput=e=>{brightness=Number(e.target.value);draw()};$('reset-image').onclick=reset;$('restore-sample').onclick=sample;
$('image-upload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){$('image-status').textContent='Choose a PNG, JPG, or WebP image smaller than 10 MB.';e.target.value='';return}const version=++imageVersion,url=URL.createObjectURL(f),candidate=new Image();candidate.onload=()=>{URL.revokeObjectURL(url);if(version!==imageVersion)return;if(candidate.naturalWidth*candidate.naturalHeight>40000000){$('image-status').textContent='Please choose an image smaller than 40 megapixels.';return}image=candidate;custom=true;reset();$('image-name').textContent='YOUR IMAGE · LOCAL ONLY';$('image-caption').textContent=f.name;$('restore-sample').hidden=false;$('image-status').textContent='Image loaded. Try a transformation; no model prediction is made.'};candidate.onerror=()=>{URL.revokeObjectURL(url);if(version===imageVersion)$('image-status').textContent='That image could not be read. Try a different file.'};candidate.src=url};
$('download-image').onclick=()=>{if(!image.complete||!image.naturalWidth)return;canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='tissue-lab-transformation.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};
let timer=null;
function stopPlay(){if(timer)clearInterval(timer);timer=null;$('play').textContent='▶ Play';$('play').setAttribute('aria-label','Play training history')}
function chart(){const run=data.runs[Number($('run').value)],rows=run.epochs,ep=Math.min(Number($('epoch').value),rows.length),row=rows[ep-1],best=Math.max(...rows.map(r=>r.val_accuracy));$('epoch').max=rows.length;$('epoch').value=ep;$('epoch-number').textContent=ep+' / '+rows.length;$('epoch-output').value=ep;$('train-value').textContent=(row.accuracy*100).toFixed(2)+'%';$('validation-value').textContent=(row.val_accuracy*100).toFixed(2)+'%';$('best-value').textContent=(best*100).toFixed(2)+'%';const x=i=>60+i/(rows.length-1)*900,y=v=>280-v*240;let s='<rect width="1000" height="330" fill="white"/>';for(let v=0;v<=1.01;v+=.25){s+=`<line x1="60" y1="${y(v)}" x2="960" y2="${y(v)}" stroke="#e4e7df"/><text x="47" y="${y(v)+4}" text-anchor="end" fill="#61726a" font-size="12">${Math.round(v*100)}%</text>`}for(let i=0;i<rows.length;i++){if(i===0||(i+1)%5===0)s+=`<text x="${x(i)}" y="307" text-anchor="middle" fill="#61726a" font-size="12">${i+1}</text>`}for(const [key,color]of[['accuracy','#245d48'],['val_accuracy','#b47085']]){s+=`<polyline points="${rows.map((r,i)=>`${x(i)},${y(r[key])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2" opacity=".18"/><polyline points="${rows.slice(0,ep).map((r,i)=>`${x(i)},${y(r[key])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/><circle cx="${x(ep-1)}" cy="${y(row[key])}" r="5" fill="${color}"/>`}s+=`<line x1="${x(ep-1)}" y1="30" x2="${x(ep-1)}" y2="280" stroke="#61726a" stroke-dasharray="3 5" opacity=".5"/>`;$('chart').innerHTML=s;$('chart').setAttribute('aria-label',`${run.name}, epoch ${ep}: training accuracy ${(row.accuracy*100).toFixed(2)} percent, validation accuracy ${(row.val_accuracy*100).toFixed(2)} percent.`)}
$('epoch').oninput=()=>{stopPlay();chart()};$('run').onchange=()=>{stopPlay();$('epoch').value=1;chart()};$('play').onclick=()=>{if(timer){stopPlay();return}if(Number($('epoch').value)>=Number($('epoch').max))$('epoch').value=1;chart();$('play').textContent='Ⅱ Pause';$('play').setAttribute('aria-label','Pause training history');timer=setInterval(()=>{const next=Number($('epoch').value)+1;if(next>Number($('epoch').max)){stopPlay();return}$('epoch').value=next;chart()},450)};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPlay()});sample();chart();

