'use strict';
(()=>{
const el=id=>document.getElementById(id);let metrics,sessionPromise,sourceVersion=0,currentSample=null,readyImage=false,liveBlob=null;
const picture=el('live-image'),run=el('classify'),status=el('inference-status');
function invalidate(){sourceVersion++;el('live-result').hidden=true;readyImage=false;run.disabled=true;status.textContent='Loading image…';}
function ready(){readyImage=true;run.disabled=!metrics;status.textContent='Ready. Click Run classification to calculate a new prediction.';}
picture.onload=ready;picture.onerror=()=>{readyImage=false;run.disabled=true;status.textContent='The image could not be loaded. Try another example.'};
function loadSample(index){invalidate();if(liveBlob){URL.revokeObjectURL(liveBlob);liveBlob=null}currentSample=metrics.samples[index];picture.src=currentSample.path;picture.alt='Held-out example with dataset label '+currentSample.label;el('sample-description').textContent='Dataset label: '+currentSample.label+'. '+currentSample.selection;el('live-upload').value='';}
function loadSession(){if(!sessionPromise){ort.env.wasm.wasmPaths=new URL('./',document.baseURI).href;ort.env.wasm.numThreads=1;sessionPromise=ort.InferenceSession.create('tissue-model.onnx',{executionProviders:['wasm'],graphOptimizationLevel:'all'}).catch(error=>{sessionPromise=null;throw error})}return sessionPromise}
function showScores(scores){const ranked=[...scores].map((score,i)=>({score,label:metrics.classes[i]})).sort((a,b)=>b.score-a.score);el('live-prediction').textContent=ranked[0].label;el('live-score').textContent=(ranked[0].score*100).toFixed(1)+'%';el('live-bars').replaceChildren();ranked.forEach(({score,label},i)=>{const row=document.createElement('div');row.className='prob-row'+(i===0?' top':'');const name=document.createElement('span');name.textContent=label;const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill';fill.style.width=(score*100)+'%';track.append(fill);const value=document.createElement('output');value.textContent=(score*100).toFixed(1)+'%';row.append(name,track,value);el('live-bars').append(row)});el('live-truth').replaceChildren();const truth=document.createElement('span');truth.textContent=currentSample?'Dataset label: '+currentSample.label:'Uploaded image · ground truth unknown';el('live-truth').append(truth);if(currentSample){const match=document.createElement('span');const correct=ranked[0].label===currentSample.label;match.className=correct?'correct':'incorrect';match.textContent=correct?'Matches label':'Does not match label';el('live-truth').append(match)}el('live-result').hidden=false;}
run.onclick=async()=>{if(!readyImage||!metrics)return;const version=sourceVersion;run.disabled=true;el('live-result').hidden=true;status.textContent=sessionPromise?'Running model on this image…':'Downloading and loading the model… first run may take a moment.';try{const session=await loadSession();if(version!==sourceVersion)return;const c=document.createElement('canvas');c.width=c.height=224;const context=c.getContext('2d',{willReadFrequently:true});context.fillStyle='#fff';context.fillRect(0,0,224,224);context.drawImage(picture,0,0,224,224);const rgba=context.getImageData(0,0,224,224).data;const pixels=new Float32Array(3*224*224);for(let i=0;i<224*224;i++){pixels[i]=rgba[i*4];pixels[i+224*224]=rgba[i*4+1];pixels[i+2*224*224]=rgba[i*4+2]}const start=performance.now();const input=new ort.Tensor('float32',pixels,[1,3,224,224]);const result=await session.run({pixels:input});const scores=Array.from(result.probabilities.data);const elapsed=performance.now()-start;input.dispose();Object.values(result).forEach(t=>t.dispose());if(version!==sourceVersion)return;if(scores.length!==8||scores.some(x=>!Number.isFinite(x)))throw Error('Invalid model output');showScores(scores);el('inference-time').textContent='Computed on your device in '+(elapsed/1000).toFixed(2)+' s. No image was uploaded to a server.';status.textContent='Classification complete.';}catch(error){if(version===sourceVersion)status.textContent='The model could not run. Check your connection and try again. No prediction has been generated.';console.error('Inference failed:',error)}finally{if(version===sourceVersion)run.disabled=!readyImage;}};
el('sample-select').onchange=e=>loadSample(Number(e.target.value));
el('live-upload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){status.textContent='Choose a PNG, JPG, or WebP image smaller than 10 MB.';e.target.value='';return}invalidate();currentSample=null;if(liveBlob)URL.revokeObjectURL(liveBlob);liveBlob=URL.createObjectURL(f);const candidate=new Image(),version=sourceVersion;candidate.onload=()=>{if(version!==sourceVersion)return;if(candidate.naturalWidth*candidate.naturalHeight>40000000){status.textContent='Please choose an image below 40 megapixels.';URL.revokeObjectURL(liveBlob);return}picture.src=liveBlob;picture.alt='Uploaded tissue image';el('sample-select').selectedIndex=-1;el('sample-description').textContent=f.name+' · resized to 224 × 224 for this model. Use square histology patches.';};candidate.onerror=()=>{if(version===sourceVersion)status.textContent='The image could not be read. Select another file.'};candidate.src=liveBlob;};
fetch('metrics.json').then(r=>{if(!r.ok)throw Error('Metrics unavailable');return r.json()}).then(m=>{metrics=m;const pct=n=>(n*100).toFixed(1)+'%';el('hero-accuracy').textContent=pct(m.test_accuracy);el('hero-test-count').textContent=m.split.test;el('test-accuracy').textContent=pct(m.test_accuracy);el('test-correct').textContent=m.test_correct+' of '+m.split.test+' images correct';el('tumor-recall').textContent=pct(m.classification_report.tumor.recall);el('tumor-support').textContent='Among '+m.classification_report.tumor.support+' tumor-labeled test images';el('split-size').textContent=m.split.training+' / '+m.split.validation+' / '+m.split.test;el('evaluation-method').textContent='A fixed MobileNetV3 Small encoder was pretrained on ImageNet. The new tissue head was trained only on '+m.split.training+' images and their augmented views. Validation loss on '+m.split.validation+' separate images selected epoch '+m.best_epoch+'. The reserved '+m.split.test+' test images were evaluated after model selection. '+m.exact_duplicates_removed+' exact duplicate images were removed before splitting.';const select=el('sample-select');select.replaceChildren();m.samples.forEach((s,i)=>{const option=document.createElement('option');option.value=i;option.textContent=s.correct?s.label+' · held-out sample':s.label+' · known error';select.append(option)});const tumorIndex=m.samples.findIndex(s=>s.label==='tumor'&&s.correct);select.value=tumorIndex>=0?tumorIndex:0;select.disabled=false;loadSample(Number(select.value));const option=document.createElement('option');option.value=window.NOTEBOOK_DATA.runs.length;option.textContent='New model · '+m.history.length+' epochs';el('run').append(option);window.NOTEBOOK_DATA.runs.push({name:'New MobileNetV3 head',epochs:m.history});el('run').value=option.value;el('epoch').max=m.history.length;el('epoch').value=m.best_epoch;chart();}).catch(()=>{status.textContent='Model details could not load. Refresh to try again.';});
})();
